container:
  cpu: 1
  memory: 2G

pipe:
  name: Build Site and Validate Links
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  allow_failures: true
  steps:
    - image: ghcr.io/squidfunk/mkdocs-material:latest
      install_script: python3 -m pip install --upgrade -r requirements.txt
      build_script: mkdocs build
      site_artifacts:
        path: "site/**"
    - image: fkorotkov/liche:latest
      validate_script: /liche --concurrency 2 --document-root=site --recursive site/

task:
  name: Markdown Lint
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  container:
    image: node:latest
  install_script: npm install -g markdownlint-cli
  lint_script: markdownlint --config=.markdownlint.yml docs/

task:
  name: Spell Check
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  container:
    image: node:latest
  install_tool_script:
    # WARNING: DO NOT try to cache this, symlinks will not be created and task will fail
    - npm install -g markdown-spellcheck@1.3.1
  spellcheck_script: mdspell '**/*.md' '!**/legal/*.md' --ignore-numbers --ignore-acronyms --report --en-us;
  env:
    FORCE_COLOR: 1

task:
  name: Deploy
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - Build Site and Validate Links
    - Markdown Lint
    - Spell Check
  container:
    image: ghcr.io/cirruslabs/mkdocs-material-insiders:latest
    registry_config: ENCRYPTED[!cf1a0f25325aa75bad3ce6ebc890bc53eb0044c02efa70d8cefb83ba9766275a994b4831706c52630a0692b2fa9cfb9e!]
  env:
    DEPLOY_TOKEN: ENCRYPTED[!45ed45666558902ed1c2400add734ec063103bec31841847e8c8764802fca229bfa6d85c690e16ad159e047574b48793!]
  install_script: python3 -m pip install --upgrade -r requirements.txt
  deploy_script: ./.ci/deploy.sh
