container:
  cpu: 1
  memory: 2G

pipe:
  name: Build Site and Validate Links
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  steps:
    - image: ghcr.io/squidfunk/mkdocs-material:latest
      install_script: python3 -m pip install --upgrade -r requirements.txt
      build_script: mkdocs build
      site_artifact:
        path: "site/**"
    - image: raviqqe/liche:latest
      validate_script: /liche --concurrency 8 --document-root=site --recursive site/

task:
  name: Markdown Lint
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  container:
    image: node:latest
  install_script: npm install -g markdownlint-cli
  lint_script: markdownlint --config=.markdownlint.yml docs/

task:
  name: Spell Check
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  container:
    image: node:latest
  install_tool_script:
    # WARNING: DO NOT try to cache this, symlinks will not be created and task will fail
    - npm install -g markdown-spellcheck@1.3.1
  spellcheck_script: mdspell '**/*.md' '!**/legal/*.md' --ignore-numbers --ignore-acronyms --report --en-us;

task:
  name: Deploy
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - Build Site and Validate Links
    - Markdown Lint
    - Spell Check
  container:
    image: ghcr.io/squidfunk/mkdocs-material-insiders:latest
    registry_config: ENCRYPTED[!eca1f54076ecc1d8721532d2610a6593d14c72289e1545a69a7e893411a2941c3ee92179a4900b90a21bee78a212b4df!]
  env:
    DEPLOY_TOKEN: ENCRYPTED[177bcd0bea94a30fd6f1ac437b8c6a633b814da46b70892c9650577051e4d043a232a573b326523178074c96c9253313]
  install_script: python3 -m pip install --upgrade -r requirements.txt
  deploy_script: ./.ci/deploy.sh
