container:
  image: squidfunk/mkdocs-material:latest

build_task:
  only_if: $CIRRUS_BRANCH != 'gh-pages' && $CIRRUS_BRANCH != 'master'
  install_script: pip install pymdown-extensions
  build_script: mkdocs build

deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  env:
    DEPLOY_TOKEN: ENCRYPTED[fbf2f9b7dc97cc3d960126b1540f19c36b96768c46b8eb99389e02b8c54080418d1fb90094dc2e3a36767df34acb5d5d]
  install_script: pip install pymdown-extensions
  deploy_script: ./.ci/deploy.sh
